name = "ghost-markdown-worker"
main = "src/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Set your Ghost blog domain here
routes = [{ pattern = "adamandlinds.com/*", zone_name = "adamandlinds.com" }]

[vars]
GHOST_URL = "https://adamandlinds.com"